Repository MIT-Emerging-Talent/ET6-CDSP-group-20-repo, pull requests merged in 2025-07, with the labels that each got.

#68 Fevzi retrospective
  1_datasets/script/app_review_scraper_guide.md
  collaboration/retrospectives/2_data_collection.md
Labels: documentation

#72 Added meeting notes for all meetings
  collaboration/meeting_notes/2025_05_31_meeting_summary.md
  collaboration/meeting_notes/2025_06_08_meeting_summary.md
  collaboration/meeting_notes/2025_06_09_meeting_summary.md
  collaboration/meeting_notes/2025_06_11_meeting_summary.md
  collaboration/meeting_notes/2025_06_12_meeting_summary.md
  collaboration/meeting_notes/2025_06_13_meeeting_summary.md
  collaboration/meeting_notes/2025_06_18_meeting_summary.md
  collaboration/meeting_notes/2025_06_19_meeting_summary.md
  collaboration/meeting_notes/2025_06_21_meeting_summary.md
  collaboration/meeting_notes/2025_06_23_meeting_summary.md
Labels: documentation

#78 Feature/exploration notebooks
  3_data_exploration/README.md
  3_data_exploration/baseline-analysis-final (2).ipynb
  3_data_exploration/comparative-analysis-final.ipynb
  3_data_exploration/conversational-apps-final (2).ipynb
Labels: documentation, enhancement

#81 data exploration readme
  3_data_exploration/README.md
Labels: documentation

#86 Add app based comparative analysis
  3_data_exploration/README.md
  3_data_exploration/app-based-comparative-analysis4.ipynb
Labels: documentation

#90 data explore huda
  3_data_exploration/README.md
  3_data_exploration/conversational_app.ipynb
Labels: documentation

#95 [docs] group and individual retrospective
  collaboration/retrospectives/3_data_analysis.md
Labels: documentation, retrospective

#96 93 documentation
  4_data_analysis/README.md
Labels: documentation

#92 Master notebook
  4_data_analysis/the-conversational-ai-tax-a-comparative-analysis.ipynb
Labels: enhancement

#106 refined problem statment & deleted initial_questions folder
  0_domain_study/initial_questions.md
  0_domain_study/problem_statement.md
Labels: documentation, cleanup
