Repository MIT-Emerging-Talent/ET6-CDSP-group-20-repo, pull requests merged in 2025-06, with the labels that each got.

#9 Updated Constraints
  collaboration/constraints.md
Labels: documentation

#11 Group Norms(Saddam)
  collaboration/README.md
Labels: documentation, enhancement

#12 Communication
  collaboration/communication.md
Labels: documentation

#15 Individual learning goals
  collaboration/learning_goals.md
Labels: documentation

#29 Update README.md
  README.md
Labels: documentation

#33 Constraints milestone 1
  0_domain_study/constraints.md
  collaboration/constraints.md
Labels: documentation

#37 Summary of our understanding of the problem domain
  0_domain_study/summary_of_our_understanding_of_the_problem_domain.md
Labels: documentation

#43 Added the research questions and updated 0_domain_study's reamde file with my part
  0_domain_study/README.md
  0_domain_study/research_question.md
Labels: documentation

#36 update_Availability
  collaboration/communication.md
Labels: documentation

#49 Editing main readme 2
  0_domain_study/retrospective.md
  README.md
Labels: enhancement

#52 Final version of README in 0_domain_study
  0_domain_study/README.md
  0_domain_study/technical_glossary.md
Labels: enhancement

#53 [docs] add retrospective-1, group-norms
  README.md
  collaboration/group_norms.md
  collaboration/retrospectives/0_cross_cultural_collaboration.md
Labels: documentation

#59 [fix] refine research question
  0_domain_study/literature_review.md
  0_domain_study/research_question.md
Labels: documentation

#61 Project methodology and data documentation
  1_datasets/README.md
  1_datasets/data_collection.md
  1_datasets/script/preprocess_data.py
  1_datasets/script/scrape_apple_app_store.py
  1_datasets/script/scrape_google_play.py
  1_datasets/script/scrape_reddit.py
Labels: documentation, enhancement

#63 [feat] add collaboration\retrospectives\2_data_collection.md, edit ma…
  README.md
  collaboration/retrospectives/2_data_collection.md
Labels: documentation, retrospective

#65 ZIZI retrospective
  collaboration/retrospectives/2_data_collection.md
Labels: documentation, discussion
